package com.lawyer.model;

public enum ERole {
	ROLE_WARDS, ROLE_NURSE, ROLE_ACCOUNTS, ROLE_CERTIFICATE, ROLE_DOCTOR, ROLE_LABRATORY, ROLE_ADMIN, ROLE_END_USER,
	ROLE_HOSPITAL_ADMIN, ROLE_AMBULANCE,ROLE_RECEPTIONIST,ROLE_PATIENT

}
